apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "cluster-autoscaler.fullname" . }}
spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ template "cluster-autoscaler.name" . }}
